rootProject.name = "JavaFeatures"
include("Java8")
include("Java9")
include("Java10")
include("Java11")
include("Java12")
include("Java13")
include("Java14")
include("Java15")
include("Java16")
include("Java17")
include("Java18")
include("Java19")
include("Java20")
include("Java21")
